### PR TITLE
Addition to the nationality

### PR DESCRIPTION
**Pull request by Annalouu**
Added the nationality since i use qb-core and the metadata was returning undefined. so i redid the function to set the metadata but i realised that its not just for qb for the idcard but a good addition none the less if triggered.

### CODE REVIEW

**Comment by Frowmza** [comment]
can u add it for esx and nd to?

**Comment by Annalouu** [comment]
Not sure, since i dont use ESX.

**Comment by Frowmza** [comment]
The reason for having a bridge is to make methods that work with all frameworks. So, just adding it to QB is pointless.

**Comment by Annalouu** [comment]
Its not pointless, since its forr QB. each framework has its own things thats the job of a bridge lol

**Pull request closed without merging**
